### ISSUE TITLE
Trouble running after install.

### ISSUE THREAD

**Issue by dan-rds** [ejmichaud/elephant#8]
After I ran the clone, cd and pip install, I got this message when trying to run any elephant command (other than just `$ elephant`) such as:
`daniel@eduroam-169-233-152-187:~/projects/elephant$elephant ls
Traceback (most recent call last):
  File "/anaconda3/bin/elephant", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/elephant.py", line 118, in ls
    c.execute('SELECT * FROM cards LIMIT ?', (limit,))
sqlite3.OperationalError: no such table: cards`

My environment: Python=3.7, conda=4.5.12, OSX=Mojave

**Comment by ejmichaud** [comment]
Hmm that's curious. Could you try installing again? I've added a new step to the installation instructions. If you could test the application both before and after running `. db_init.sh`, that would be very help. Thanks Daniel!

**Comment by ejmichaud** [comment]
Hey Daniel - did you just graduate?? I think I might have really fixed this issue ^^. Want to try again?
